In [66]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv("powerplant_data.csv")

In [68]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB

In [70]:
# AT => Temperature
# V => Vacuum
# AP => Pressure
# RH => Humidity

# PE => Produced Energy

In [71]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [72]:
X = df.drop("PE", axis=1)
y = df["PE"]

In [73]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [75]:
X_train

         AT      V       AP     RH
5487  25.24  63.47  1011.30  66.21
3522  26.09  70.40  1007.41  85.37
6916  26.63  73.68  1015.15  85.13
7544  32.06  71.85  1007.90  56.44
7600  28.70  71.64  1007.11  69.85
...     ...    ...      ...    ...
5734  26.25  61.02  1011.47  71.22
5191  29.17  64.79  1016.43  61.05
5390  18.00  43.70  1015.40  61.28
860   26.73  68.84  1010.75  66.83
7270   6.40  39.18  1024.60  86.83

[7654 rows x 4 columns]

In [76]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [77]:
import torch
import torch.nn as nn

In [78]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1,1)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1,1)

In [79]:
from torch.utils.data import TensorDataset, DataLoader

In [80]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [81]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

Deep Learninng

In [82]:
# Define our ANN Model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()
        self.model = nn.Sequential(
            # 1st hidden layer
            nn.Linear(X_train.shape[1], 6),
            nn.ReLU(),

            # 2nd hidden layer
            nn.Linear(6, 6),
            nn.ReLU(),

            # Output layer
            nn.Linear(6, 1),
        )

    def forward(self, x):
        return self.model(x)

In [83]:
import torch.optim as optim

model = ANN()

#losses, optimizer
crietrion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

In [84]:
#Train th eANN
train_losses = []
val_losses = []
epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0 #total traning loss for 1 epoch

    for xb, yb in train_loader:
        #xb = feature of 1 batch
        #yb = labels of 1 batch
        optimizer.zero_grad()

        outputs = model(xb) # forward prop.. predictes outputs for this batch
        loss = crietrion(outputs, yb) #complete loss
        loss.backward() #back prop.. complete gradients
        optimizer.step() #parameter update

        running_loss += loss.item() #loss is a tensor => python float
    epoch_train_loss = running_loss / len(train_loader)
    train_losses.append(epoch_train_loss)

    #Validation 
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad(): #no gradients compute
        for xb, yb in test_loader:
            outputs = model(xb) 
            loss = crietrion(outputs, yb)
            running_val_loss += loss

    epoch_val_loss = running_val_loss / len(test_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss} & val loss = {epoch_val_loss}")

epoch 1/100 ==> train loss = 206344.70904947916 & val loss = 204631.140625
epoch 2/100 ==> train loss = 198838.7896484375 & val loss = 188946.515625
epoch 3/100 ==> train loss = 170591.04342447917 & val loss = 148342.46875
epoch 4/100 ==> train loss = 123790.46907552083 & val loss = 100619.5
epoch 5/100 ==> train loss = 83312.78063151041 & val loss = 69651.4140625
epoch 6/100 ==> train loss = 59131.66713867187 & val loss = 50054.4453125
epoch 7/100 ==> train loss = 41106.780436197914 & val loss = 32878.3203125
epoch 8/100 ==> train loss = 25368.332873535157 & val loss = 18813.912109375
epoch 9/100 ==> train loss = 13999.040340169271 & val loss = 10067.8642578125
epoch 10/100 ==> train loss = 7827.764705403646 & val loss = 5832.775390625
epoch 11/100 ==> train loss = 4823.766035970052 & val loss = 3751.468505859375
epoch 12/100 ==> train loss = 3192.622019958496 & val loss = 2586.079833984375
epoch 13/100 ==> train loss = 2249.994907124837 & val loss = 1910.8414306640625
epoch 14/100 ==> train loss = 1680.1352912902832 & val loss = 1492.309814453125
epoch 15/100 ==> train loss = 1320.5219857533773 & val loss = 1206.1551513671875
epoch 16/100 ==> train loss = 1068.6858921051025 & val loss = 993.5648193359375
epoch 17/100 ==> train loss = 881.8644442240397 & val loss = 822.081787109375
epoch 18/100 ==> train loss = 729.4223452250163 & val loss = 682.5379638671875
epoch 19/100 ==> train loss = 610.9048402150472 & val loss = 569.9904174804688
epoch 20/100 ==> train loss = 512.2019123077392 & val loss = 477.74310302734375
epoch 21/100 ==> train loss = 431.2179917017619 & val loss = 401.04205322265625
epoch 22/100 ==> train loss = 363.6754870096842 & val loss = 337.1661071777344
epoch 23/100 ==> train loss = 305.10515311559044 & val loss = 284.2330017089844
epoch 24/100 ==> train loss = 256.6783037185669 & val loss = 238.6517791748047
epoch 25/100 ==> train loss = 216.2564014116923 & val loss = 199.694580078125
epoch 26/100 ==> train loss = 181.1356079896291 & val loss = 166.69525146484375
epoch 27/100 ==> train loss = 150.48854723771413 & val loss = 139.1185760498047
epoch 28/100 ==> train loss = 125.76584046681722 & val loss = 116.87212371826172
epoch 29/100 ==> train loss = 104.39716014067332 & val loss = 96.48422241210938
epoch 30/100 ==> train loss = 86.61699821154276 & val loss = 80.0704574584961
epoch 31/100 ==> train loss = 71.57938125133515 & val loss = 66.06752014160156
epoch 32/100 ==> train loss = 59.31382744312286 & val loss = 54.63044738769531
epoch 33/100 ==> train loss = 49.68109532197317 & val loss = 45.27222442626953
epoch 34/100 ==> train loss = 41.85982784430186 & val loss = 38.10056686401367
epoch 35/100 ==> train loss = 35.55944127639135 & val loss = 32.576271057128906
epoch 36/100 ==> train loss = 31.00200689236323 & val loss = 28.614408493041992
epoch 37/100 ==> train loss = 27.526380554835 & val loss = 25.389375686645508
epoch 38/100 ==> train loss = 25.038864847024282 & val loss = 23.72364616394043
epoch 39/100 ==> train loss = 23.35580347776413 & val loss = 21.401525497436523
epoch 40/100 ==> train loss = 22.124464412530262 & val loss = 20.51814079284668
epoch 41/100 ==> train loss = 21.238542314370473 & val loss = 20.03247833251953
epoch 42/100 ==> train loss = 20.6797476708889 & val loss = 19.834577560424805
epoch 43/100 ==> train loss = 20.319521061579387 & val loss = 19.10770034790039
epoch 44/100 ==> train loss = 20.043124119440716 & val loss = 19.537443161010742
epoch 45/100 ==> train loss = 19.933545899391174 & val loss = 18.422971725463867
epoch 46/100 ==> train loss = 19.860703659057616 & val loss = 18.60825538635254
epoch 47/100 ==> train loss = 19.78027007977168 & val loss = 18.842798233032227
epoch 48/100 ==> train loss = 19.76923335790634 & val loss = 19.497692108154297
epoch 49/100 ==> train loss = 19.685435287157695 & val loss = 18.744892120361328
epoch 50/100 ==> train loss = 19.615379369258882 & val loss = 18.61131477355957
epoch 51/100 ==> train loss = 19.59697423775991 & val loss = 18.47377586364746
epoch 52/100 ==> train loss = 19.630412459373474 & val loss = 18.519542694091797
epoch 53/100 ==> train loss = 19.75638356208801 & val loss = 18.21463394165039
epoch 54/100 ==> train loss = 19.66146332025528 & val loss = 18.518579483032227
epoch 55/100 ==> train loss = 19.538452736536662 & val loss = 18.343229293823242
epoch 56/100 ==> train loss = 19.588173019886018 & val loss = 19.169721603393555
epoch 57/100 ==> train loss = 19.57823993762334 & val loss = 19.228044509887695
epoch 58/100 ==> train loss = 19.582950282096864 & val loss = 18.160442352294922
epoch 59/100 ==> train loss = 19.513188405831656 & val loss = 18.139902114868164
epoch 60/100 ==> train loss = 19.42134316364924 & val loss = 18.398618698120117
epoch 61/100 ==> train loss = 19.549166818459828 & val loss = 18.540042877197266
epoch 62/100 ==> train loss = 19.565127301216126 & val loss = 18.294469833374023
epoch 63/100 ==> train loss = 19.46563107172648 & val loss = 18.122901916503906
epoch 64/100 ==> train loss = 19.59246129989624 & val loss = 18.766658782958984
epoch 65/100 ==> train loss = 19.493112929662068 & val loss = 18.051307678222656
epoch 66/100 ==> train loss = 19.2786642630895 & val loss = 17.931785583496094
epoch 67/100 ==> train loss = 19.377977828184765 & val loss = 18.01850700378418
epoch 68/100 ==> train loss = 19.347257900238038 & val loss = 18.22710418701172
epoch 69/100 ==> train loss = 19.41508552233378 & val loss = 18.473569869995117
epoch 70/100 ==> train loss = 19.355030818780264 & val loss = 18.108070373535156
epoch 71/100 ==> train loss = 19.431254982948303 & val loss = 19.806129455566406
epoch 72/100 ==> train loss = 19.2923006216685 & val loss = 17.799104690551758
epoch 73/100 ==> train loss = 19.4366175532341 & val loss = 18.466875076293945
epoch 74/100 ==> train loss = 19.284096421798072 & val loss = 17.85375213623047
epoch 75/100 ==> train loss = 19.22691474358241 & val loss = 18.118623733520508
epoch 76/100 ==> train loss = 19.162414169311525 & val loss = 18.749908447265625
epoch 77/100 ==> train loss = 19.391935942570367 & val loss = 17.730037689208984
epoch 78/100 ==> train loss = 19.21942016084989 & val loss = 17.99544334411621
epoch 79/100 ==> train loss = 19.27564279238383 & val loss = 17.882932662963867
epoch 80/100 ==> train loss = 19.224086689949036 & val loss = 18.546916961669922
epoch 81/100 ==> train loss = 19.597101787726086 & val loss = 17.657033920288086
epoch 82/100 ==> train loss = 19.194881121317547 & val loss = 17.72632598876953
epoch 83/100 ==> train loss = 19.210737689336142 & val loss = 17.685575485229492
epoch 84/100 ==> train loss = 19.29980467756589 & val loss = 18.569429397583008
epoch 85/100 ==> train loss = 19.375918050607044 & val loss = 18.655393600463867
epoch 86/100 ==> train loss = 19.267736728986105 & val loss = 18.206050872802734
epoch 87/100 ==> train loss = 19.2437665104866 & val loss = 18.02470588684082
epoch 88/100 ==> train loss = 19.203149350484214 & val loss = 17.944988250732422
epoch 89/100 ==> train loss = 19.15230583747228 & val loss = 18.2923583984375
epoch 90/100 ==> train loss = 19.302131472031274 & val loss = 17.574506759643555
epoch 91/100 ==> train loss = 19.040782749652863 & val loss = 18.12522315979004
epoch 92/100 ==> train loss = 19.099843949079514 & val loss = 17.874839782714844
epoch 93/100 ==> train loss = 19.165999948978424 & val loss = 17.490373611450195
epoch 94/100 ==> train loss = 19.193791361649833 & val loss = 18.277849197387695
epoch 95/100 ==> train loss = 19.050724015633264 & val loss = 17.645490646362305
epoch 96/100 ==> train loss = 19.075823561350504 & val loss = 18.229209899902344
epoch 97/100 ==> train loss = 19.153955992062887 & val loss = 17.765989303588867
epoch 98/100 ==> train loss = 19.069522655010225 & val loss = 17.81545639038086
epoch 99/100 ==> train loss = 19.126427857081094 & val loss = 17.65938377380371
epoch 100/100 ==> train loss = 19.045740044116975 & val loss = 17.41410255432129